theme: minima
title: My first github pages
author: sukumar1612
email: suku1612@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  learning to make github pages.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
future: true
